#add this file sync_to_HF_hub.yml to the workflows in actions github
# as in image2textapp github from amrrs
name: main

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.image2ocr }}
        run: git push --force https://Amrrs:$image2ocr@https://huggingface.co/spaces/AItool/Image2OCR main
